# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lucas de Sá
title: Ph.D. Candidate in Astronomy, University of São Paulo
email: lucasmdesa@usp.br
website: lucasmdesa.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: lucasmdesa
github_username:  lmdesa
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: gardelpesquisa
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-3109-9042

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Personal webpage, WIP!

content:
	- title: Projects # Title for the section
  	layout: list # Type of content section (list/text)
    content:
    	- layout: top-middle
        title: Compact object populations over cosmic time
        link: soon
        # link_text: Project Website
        additional_links:
        	- title:  sproogen/modern-resume-theme
          	icon: fab fa-github
          	url: github.com/sproogen/modern-resume-theme
          	# - title:  Github page for project (eg. sproogen/modern-resume-theme)
          	#   icon: fab fa-github
          	#   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Main PhD project
      - layout: top-middle
        title: Compact objects masses
        link: soon
        # link_text: Project Website
        additional_links:
        	- title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          ...
        description: | # this will include new lines to allow paragraphs
          Objects in the mass gap; stellar BH masses.
  
	- title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of São Paulo
        caption: 2021 - 2025 (expected)
        sub_title: PhD Astronomy
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          Compact object populations over cosmic time
      - layout: left
        title: University of São Paulo
        caption: 2017 - 2020
        sub_title: BSc Physics
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          Machine learning optimization of a magneto-optical trap
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Somehow it all started with Bose-Einstein condensates...

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
